
language: java
jdk: oraclejdk8

sudo: required

cache:
  directories:
  - .gradle
  - $HOME/.gradle

services:
  - mongodb
  - rabbitmq

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick librsvg2-bin

before_script:
  - tar -Jxvf ${TRAVIS_BUILD_DIR}/src/test/db.txz
  - mongorestore ${TRAVIS_BUILD_DIR}/dump/
#  - ln --symbolic ${TRAVIS_BUILD_DIR}/gradle/wrapper ${TRAVIS_BUILD_DIR}/gradlew

script:
  - gradle/wrapper --info --stacktrace site

after_success: bash <(curl -s https://codecov.io/bash)
