#
# TODO Generate site and deploy from Travis CI (use `deploy` option to deploy on `master` push)
#

language: java
jdk: oraclejdk8
sudo: required # Container build is slower than sudo

branches:
  only:
    - master
    - develop

before_cache:
  - rm -f  $HOME/.gradle/caches/*/*.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts*/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/

services:
  - mongodb
  - rabbitmq
  - postgresql

install:
  - echo "ext.ci = true" >local.gradle
  - mongo hexagon_benchmark/mongodb.js
  - psql -U postgres -f hexagon_benchmark/postgresql.sql

script: ./gradlew --no-daemon clean site installDist jacocoReport installAllTemplates tfb

after_success: bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
#  script: ./gradlew --no-daemon release
  script: ./gradlew --no-daemon hexagon_site:gitPublishPush
  on:
    branch: master
