#
# Site generation does not work well with Gradle daemon. Execute it this way:
#     gw --no-daemon site
#

language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/native
  - $HOME/.gradle/daemon
  - $HOME/.gradle/caches/jars-1
  - $HOME/.gradle/caches/3.0

services:
  - mongodb
  - rabbitmq

script:
  - gradle/wrapper --no-daemon --stacktrace site

after_success: bash <(curl -s https://codecov.io/bash)
