#
# Site generation does not work well with Gradle daemon. Execute it this way:
#     gw --no-daemon site
#

language: java
jdk: oraclejdk8

sudo: required

cache:
  directories:
  - .gradle
  - $HOME/.gradle

services:
  - mongodb
  - rabbitmq

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick librsvg2-bin

before_script:
  - tar -Jxvf ${TRAVIS_BUILD_DIR}/benchmark/db.txz
  - mongorestore ${TRAVIS_BUILD_DIR}/dump/

script:
  - gradle/wrapper --info --stacktrace -x test publishToMavenLocal
  - gradle/wrapper --info --stacktrace build
  - gradle/wrapper --no-daemon --info --stacktrace site

after_success: bash <(curl -s https://codecov.io/bash)
