#
# TODO Caching is slower than sudo: required
# TODO Generate site and deploy from Travis CI (use `deploy` option to deploy on `master` push)
#

language: java
jdk: oraclejdk8
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/daemon/
  - $HOME/.gradle/native/
  - $HOME/.gradle/wrapper/

services:
  - mongodb
  - rabbitmq

install: ln -s gradle/wrapper gradlew

script: gradle/wrapper --stacktrace build

# TODO Fix codecov (coverage reports not found)
after_success: bash <(curl -s https://codecov.io/bash)
