#
# TODO Generate site and deploy from Travis CI (use `deploy` option to deploy on `master` push)
#

language: java
jdk: oraclejdk8
sudo: required # Container build is slower than sudo

branches:
  only:
    - master
    - develop

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts*/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/

services:
  - mongodb
  - rabbitmq

install:
  - ln -s gradle/wrapper gradlew
  - mongo systems/benchmark.js
  - mysql --user=root < systems/benchmark.sql

script: gradle/wrapper --no-daemon --full-stacktrace build site

after_success: bash <(curl -s https://codecov.io/bash)
