#
# Site generation does not work well with Gradle daemon. Execute it this way:
#     gw --no-daemon site
#

language: java
jdk: oraclejdk8

cache:
  directories:
  - .gradle
  - $HOME/.gradle

services:
  - mongodb
  - rabbitmq

script:
  - gradle/wrapper --no-daemon --stacktrace site

after_success: bash <(curl -s https://codecov.io/bash)
