#
# Site generation does not work well with Gradle daemon. Execute it this way:
#     gw --no-daemon site
#

language: java
jdk: oraclejdk8

sudo: false

cache:
  directories:
  - .gradle
  - $HOME/.gradle

services:
  - mongodb
  - rabbitmq

before_script:
  - tar -Jxvf ${TRAVIS_BUILD_DIR}/benchmark/db.txz
  - mongorestore ${TRAVIS_BUILD_DIR}/benchmark/dump/

script:
  - gradle/wrapper --info --stacktrace check
  - gradle/wrapper --no-daemon --info --stacktrace javadoc jacocoTestReport site dokka

after_success: bash <(curl -s https://codecov.io/bash)
