#
# Services needed for testing
#

mongodb:
  image: mongo
  ports:
    - 27017:27017

mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
  ports:
    - 3306:3306

rabbitmq:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672
