#
# Services needed for testing (check `site/content/contribute.md`).
#

version: '3'

services:
  postgresql:
    image: postgres
    volumes:
      - ./hexagon_benchmark/postgresql.sql:/docker-entrypoint-initdb.d/db.sql:ro
    ports:
      - 5432:5432

  mongodb:
    image: mongo
    volumes:
      - ./hexagon_benchmark/mongodb.js:/docker-entrypoint-initdb.d/mongodb.js:ro
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  benchmark_resin_mongodb:
    build: { context: "./hexagon_benchmark", dockerfile: "resin.dockerfile" }
    depends_on: [ mongodb ]
    environment: [ "DBHOST=mongodb", "DBSTORE=mongodb" ]
    links: [ "mongodb:mongodb" ]
    ports: [ "9010:8080" ]

  benchmark_jetty_mongodb:
    build: { context: "./hexagon_benchmark", dockerfile: "java.dockerfile" }
    depends_on: [ mongodb ]
    environment: [ "DBHOST=mongodb", "DBSTORE=mongodb" ]
    links: [ "mongodb:mongodb" ]
    ports: [ "9020:9090" ]

  benchmark_jetty_postgresql:
    build: { context: "./hexagon_benchmark", dockerfile: "java.dockerfile" }
    depends_on: [ postgresql ]
    environment: [ "DBHOST=postgresql", "DBSTORE=postgresql" ]
    links: [ "postgresql:postgresql" ]
    ports: [ "9030:9090" ]

  benchmark_undertow_mongodb:
    build: { context: "./hexagon_benchmark", dockerfile: "java.dockerfile" }
    depends_on: [ mongodb ]
    environment: [ "DBHOST=mongodb", "WEBENGINE=undertow", "DBSTORE=mongodb" ]
    links: [ "mongodb:mongodb" ]
    ports: [ "9040:9090" ]

  benchmark_undertow_postgresql:
    build: { context: "./hexagon_benchmark", dockerfile: "java.dockerfile" }
    depends_on: [ postgresql ]
    environment: [ "DBHOST=postgresql", "WEBENGINE=undertow", "DBSTORE=postgresql" ]
    links: [ "postgresql:postgresql" ]
    ports: [ "9050:9090" ]
