#
# Services needed for testing. To setup them it is necessary to execute the following command after
# starting the containers (check `site/content/contribute.md`):
#
#     docker exec hexagon_mongodb_1 mongo /benchmark.js
#

mongodb:
  image: mongo
  volumes:
    - ./systems/benchmark.js:/benchmark.js:ro
  ports:
    - 27017:27017

rabbitmq:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672
