#
# Services needed for testing
#

mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./systems/benchmark.cnf:/etc/mysql/conf.d/config-file.cnf:ro
    - ./systems/benchmark.sql:/docker-entrypoint-initdb.d/benchmark.sql:ro
  ports:
    - 3306:3306

# docker exec -it hexagon_mongodb_1 mongo /benchmark.js
mongodb:
  image: mongo
  volumes:
    - ./systems/benchmark.js:/benchmark.js:ro
  ports:
    - 27017:27017

rabbitmq:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672
