#
# Services needed for testing (check `site/content/contribute.md`).
#

version: '3'

services:
  postgresql:
    image: postgres
    volumes:
      - ./hexagon_benchmark/postgresql.sql:/docker-entrypoint-initdb.d/db.sql:ro
    ports:
      - 5432:5432

  mongodb:
    image: mongo
    volumes:
      - ./hexagon_benchmark/mongodb.js:/docker-entrypoint-initdb.d/mongodb.js:ro
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  # TODO Make it optional
  benchmark_resin:
    build: { context: "./hexagon_benchmark", dockerfile: "resin.dockerfile" }
    depends_on: [ mongodb, postgresql ]
    environment: [ "MONGODB_DB_HOST=mongodb", "POSTGRESQL_DB_HOST=postgresql" ]
    ports: [ "9010:8080" ]

  benchmark_jetty:
    build: { context: "./hexagon_benchmark", dockerfile: "java.dockerfile" }
    depends_on: [ mongodb, postgresql ]
    environment: [ "MONGODB_DB_HOST=mongodb", "POSTGRESQL_DB_HOST=postgresql" ]
    ports: [ "9020:9090" ]

  benchmark_undertow:
    build: { context: "./hexagon_benchmark", dockerfile: "java.dockerfile" }
    depends_on: [ mongodb, postgresql ]
    environment: [ "MONGODB_DB_HOST=mongodb", "POSTGRESQL_DB_HOST=postgresql", "WEBENGINE=undertow" ]
    ports: [ "9040:9090" ]
