#
# Services needed for testing (check `site/content/contribute.md`).
#

mongodb:
  image: mongo
  volumes:
    - ./benchmark/mongodb.js:/docker-entrypoint-initdb.d/mongodb.js:ro
  ports:
    - 27017:27017

mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./benchmark/mysql.cnf:/etc/mysql/conf.d/config-file.cnf:ro
    - ./benchmark/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:ro
  ports:
    - 3306:3306

postgresql:
  image: postgres
  volumes:
    - ./benchmark/postgresql.sql:/docker-entrypoint-initdb.d/db.sql:ro
  ports:
    - 5432:5432

rabbitmq:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 15672:15672
